name: Run tests2
on:
  push:
  pull_request:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      -
        run: echo ${{ github.ref }}

  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, '/refs/tags/') }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2