name: Run tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.event }}
      - run: echo ${{ github.actor }}
      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ github.base_ref }}
      - run: echo ${{ runner.os }}
      - name: as JSON
        run: |
          echo '${{ toJSON(job) }}'
          echo "-----"
          echo '${{ toJSON(github.event) }}'
          echo "-----"
          echo '${{ toJSON(github.event.commits) }}'
          echo "-----"
          echo '${{ toJSON(runner) }}'
          echo "-----"
          echo '${{ toJSON(github) }}'
          echo "-----"
